
import type { District } from './types';

export const badlands: District = {
  name: "As Terras Baldias (Badlands): O Deserto Sem Lei",
  iconName: "MountainSnow",
  gradient: "linear-gradient(to right, #8B4513, #DAA520)",
  titleColorClass: "text-white",
  borderColor: "#8B4513",
  paragraphs: [
    "As Terras Baldias (Badlands) não são um distrito urbano de Night City, mas formam uma vasta e desolada região que cerca a metrópole, agindo como seu subúrbio mais selvagem e perigoso. Diferente das áreas urbanas controladas por corporações e gangues de rua, as Badlands são o domínio das Famílias Nômades, grupos itinerantes que vivem fora do sistema corporativo, sobrevivendo à base de caravanas, comércio e uma forte lealdade tribal. Sua história é de resistência, liberdade e uma luta constante contra a hostilidade do ambiente e a invasão corporativa.",
    "Originalmente, as áreas que compõem as Badlands eram desertos e terras agrícolas que rodeavam a então nascente Night City. Com o tempo, a expansão urbana e a poluição industrial da metrópole, somadas aos impactos das Guerras Corporativas e dos desastres ambientais, transformaram grande parte dessas terras em um deserto árido e tóxico. O solo ficou infértil, a água escassa, e o ar, muitas vezes, é carregado de resíduos industriais.",
    "Após o colapso econômico global e o aumento da violência corporativa no final do século XX e início do XXI, muitas pessoas que perderam seus empregos, suas casas e sua fé no sistema decidiram abandonar as cidades. Essas pessoas formaram as primeiras Famílias Nômades, buscando uma vida de liberdade, autossuficiência e escape das garras das megacorporações. As Badlands se tornaram seu refúgio, um lugar onde a lei era a do mais forte e onde a união da família era a única verdadeira segurança.",
    "As Badlands são governadas não por um governo ou por corporações, mas por um complexo sistema de Famílias Nômades. Essas famílias são grandes grupos de pessoas que se movem em caravanas de veículos personalizados e fortemente armados, viajando pelas estradas e desertos. Cada família tem seu próprio líder (o \"Aldecaldo\", por exemplo), suas próprias tradições, regras e especialidades. As mais proeminentes são: Aldecaldos: A maior e mais influente família Nômade, conhecida por sua coesão, seu forte senso de comunidade e sua lealdade. Eles são especialistas em transporte, contrabando e têm uma vasta rede de contatos. Saul Bright é um dos líderes mais respeitados. No jogo, V tem uma forte ligação com essa família. Wraiths: Uma gangue Nômade, mas que perdeu o senso de honra e se tornou extremamente violenta e sádica. Eles atacam caravanas, saqueiam assentamentos e são temidos por todos nas Badlands. Liderados por Dakota Smith, eles são uma ameaça constante. Forge: Outra família Nômade com reputação mais agressiva e violenta, frequentemente em conflito com outras famílias e com os Tyger Claws, embora menos proeminente que os Aldecaldos e Wraiths.",
    "A vida nômade é difícil. As famílias precisam ser autossuficientes, consertando seus próprios veículos, encontrando água e comida, e defendendo-se de outras gangues, dos Scavengers e, ocasionalmente, das incursões corporativas. A troca e o escambo são a base de sua economia, complementados por serviços de transporte e escolta, que muitas vezes envolvem contrabando para dentro e fora de Night City.",
    "Embora as Badlands sejam um território \"livre\", as megacorporações ainda tentam explorar seus recursos e usar as vastas extensões de terra para seus próprios fins. Empresas como a Zetatech e a Petrochem têm instalações de extração de recursos, refinarias de petróleo (muitas vezes antigas e degradadas) e laboratórios de pesquisa espalhados pela região, muitas vezes operando sem licença e com pouca preocupação ambiental. A Petrochem, em particular, é um grande jogador nas Badlands devido aos seus vastos campos de exploração de petróleo e gás.",
    "A Militech também mantém bases de treinamento e campos de teste de armas nas Badlands, aproveitando o terreno aberto e a ausência de leis para testar novas tecnologias e treinar suas tropas. Há uma tensão constante entre os Nômades e as forças corporativas, que ocasionalmente resultam em confrontos violentos por terra, recursos ou rotas de transporte. Os Nômades veem as corporações como a personificação da opressão que eles fugiram, e defendem seu território com ferocidade.",
    "As Badlands são um palco constante de conflitos. As Famílias Nômades frequentemente se enfrentam por territórios de caça, rotas de comércio, recursos hídricos ou por vingança devido a ataques anteriores. Os Wraiths são os maiores inimigos dos Nômades, atacando caravanas e assentamentos sem piedade, roubando suprimentos, veículos e até mesmo pessoas para vender ao mercado negro de órgãos ou escravidão. Os Scavengers também espreitam nas Badlands, caçando vítimas para seus comércios de órgãos e cibernéticos, muitas vezes se misturando entre as gangues para disfarçar suas operações.",
    "A NCPD e o governo de Night City têm praticamente zero jurisdição nas Badlands. A lei é feita pelas próprias famílias, através de seus conselhos e líderes, e pela força das armas. Não há figuras políticas formais no sentido urbano, apenas os líderes das famílias que tomam as decisões para seus respectivos grupos, negociando ou lutando com outras famílias e com as corporações.",
    "Locais Conhecidos: Solar Array: Um gigantesco complexo de painéis solares, uma das poucas estruturas de grande escala nas Badlands que ainda opera, muitas vezes sob controle de Nômades ou de pequenas corporações. Wind Farms: Áreas com grandes turbinas eólicas, que fornecem energia para algumas poucas instalações corporativas e assentamentos nômades, e são pontos estratégicos disputados. Scrapyards (Ferro-velhos): Enormes depósitos de lixo e veículos abandonados, que servem como fonte de peças para os Nômades (que são mestres em mecânica e reparos) e como esconderijos fortificados para gangues. Nomad Camps: Acampamentos temporários ou semi-permanentes das Famílias Nômades, onde eles param para descansar, comerciar e se reagrupar. Esses acampamentos são bem defendidos e representam o coração da vida nômade. Aldecaldos Camp: O acampamento principal da família Aldecaldo, que se move periodicamente, mas serve como base de operações para V durante parte de sua jornada.",
    "Em 2077, as Terras Baldias são um lembrete vívido de que a vida fora das megacidades é brutal, mas oferece uma liberdade que muitos na cidade anseiam. É um lugar onde a lealdade é tudo, a tecnologia é usada para sobreviver e a natureza indomável se choca com os restos da civilização. Para os Nômades, as Badlands são o lar, um símbolo de sua resistência contra o sistema corporativo e a busca incessante por autonomia. Eles vivem de acordo com suas próprias regras, priorizando a família e a sobrevivência em um mundo que os abandonou, mas que eles recusam a deixar dominar."
  ],
  dominantGangs: ["Aldecaldos", "Wraiths", "Forge", "Scavengers (threat)"],
  majorCorporations: ["Petrochem", "Militech", "Zetatech"]
};
