
import type { District } from './types';

export const cityCenter: District = {
  name: "City Center: O Coração de Neon do Poder Corporativo",
  iconName: "Building2",
  gradient: "linear-gradient(to right, #EAFF00, #6E7800)",
  titleColorClass: "text-black",
  borderColor: "#EAFF00",
  paragraphs: [
    "O City Center é o cérebro, o coração e a carteira de Night City, tudo em um só lugar. É o distrito que grita \"poder e grana\" em cada arranha-céu que toca as nuvens. Se Night City é uma distopia cyberpunk, o City Center é a sua versão mais pura e brutal, onde as megacorporações exercem seu domínio absoluto e a vida humana é, na melhor das hipóteses, um detalhe nas planilhas de lucros.",
    "Desde o início do projeto de Richard Night para Coronado City, a área que se tornaria o City Center foi destinada a ser o centro de poder e negócios. Durante os anos 1980 e 1990, com o crescimento exponencial das megacorporações, o City Center se transformou rapidamente em uma selva de concreto e vidro, com edifícios corporativos colossais surgindo um após o outro. A Arasaka e a Militech, as duas maiores rivais, estabeleceram suas sedes e escritórios principais aqui, transformando o horizonte em uma vitrine de sua competição e riqueza.",
    "A arquitetura do City Center é monumental, refletindo a ambição e o poder das corporações. Torres de aço e vidro, fachadas holográficas e painéis de neon gigantescos são a norma. É um lugar onde a tecnologia de ponta é exibida em cada esquina, desde os carros voadores que cortam o céu até os sistemas de segurança mais avançados.",
    "O City Center, por ser o epicentro do poder corporativo, foi também o principal palco da Quarta Guerra Corporativa (2070). Foi aqui que a rivalidade entre Arasaka e Militech atingiu seu ápice. Bombardeios aéreos, tiroteios de grande escala e sabotagens devastadoras eram parte do dia a dia. A imagem mais icônica e trágica dessa guerra é a detonação da bomba nuclear tática na Arasaka Tower em 2023, um evento cataclísmico orquestrado por ninguém menos que Johnny Silverhand e Rogue Amendiares.",
    "A explosão não só destruiu grande parte da Arasaka Tower, mas também criou a cicatriz conhecida como \"A Cratera\" no coração do City Center. Embora a Arasaka tenha reconstruído sua torre, o evento deixou uma marca indelével na paisagem e na psique de Night City, simbolizando a capacidade destrutiva das guerras corporativas. A reconstrução do City Center foi um esforço colossal, financiado pelas próprias corporações, que queriam restaurar sua imagem e seu centro de operações.",
    "Em 2077, o City Center é o domínio inquestionável das megacorporações. A Arasaka com sua torre reconstruída e segurança impenetrável, continua sendo a força dominante, controlando os sistemas bancários, a segurança e a manufatura. A Militech mantém uma forte presença, com escritórios e centros de pesquisa e desenvolvimento de armas, embora sua rivalidade com a Arasaka seja agora mais política e econômica do que bélica.",
    "Outras gigantes, como a Kang Tao (especializada em armas e tecnologia militar chinesa, com um estilo mais elegante), a Zetatech (líder em software e IA) e a Biocorp (com seus hospitais de elite e laboratórios de pesquisa) também têm uma presença significativa, controlando vastos segmentos da economia e da infraestrutura da cidade.",
    "A Trauma Team International tem sua sede principal no City Center, operando suas unidades de resgate rápido para os clientes mais ricos. Eles são um lembrete constante de que, mesmo no topo da cadeia alimentar, a vida em Night City é perigosa, e a proteção tem um preço.",
    "O governo de Night City, através do Conselho Municipal, tem seus escritórios no City Center, mas sua autoridade é amplamente simbólica. O poder real reside nas mãos dos CEOs das megacorporações, que são os verdadeiros \"figuras políticas\" da cidade. Eles tomam as decisões que afetam a vida de milhões, controlam as leis (ou as ignoram) e moldam o futuro de Night City. Lobby intenso, subornos e até mesmo assassinatos políticos são ferramentas comuns nesse jogo de poder.",
    "A NCPD no City Center é mais robusta e bem equipada do que em outros distritos, mas seu papel é principalmente proteger os interesses corporativos e manter a ordem para que os negócios continuem fluindo. A segurança privada das corporações é ainda mais presente e implacável, garantindo que nenhum elemento indesejável (ou gangues) ameace os interesses dos \"peixes grandes\".",
    "Diferente de distritos como Watson ou Japantown, o City Center não tem gangues territoriais dominantes. A presença de gangues aqui é mais sutil, geralmente ligada a roubos de alto valor, sabotagens corporativas por encomenda ou tráfico de informações e tecnologia rara. Gangues como os Voodoo Boys podem se aventurar em incursões de netrunning para roubar dados, enquanto os Maelstrom podem ser contratados para serviços de \"intimidação\" ou violência direcionada. No entanto, confrontos abertos são raros devido à segurança massiva e à resposta imediata das forças corporativas e da NCPD.",
    "Além da Arasaka Tower, outros marcos incluem o Night City Financial Center, que abriga as maiores bolsas de valores e instituições financeiras. O Downtown é uma área de escritórios e hotéis de luxo, onde a vida noturna é exclusiva e voltada para a elite. O Corpo Plaza é a praça central, cercada por arranha-céus, que simboliza o poderio corporativo. Há também inúmeros megabuildings com apartamentos caríssimos, galerias de arte de ponta e restaurantes com estrelas Michelin.",
    "Em 2077, o City Center é o ápice da distopia cyberpunk: um lugar de riqueza inigualável e avanço tecnológico estonteante, construído sobre as ruínas de guerras passadas e mantido pelo controle implacável das megacorporações. É o sonho americano, mas com um preço que pouquíssimos podem pagar e muitos mais estão dispostos a morrer para alcançar."
  ],
  dominantGangs: [],
  majorCorporations: ["Arasaka", "Militech", "Kang Tao", "Zetatech", "Biotechnica", "Trauma Team International", "Night Corp"]
};
