
import type { District } from './types';

export const dogtown: District = {
  name: "Dogtown: O Feudo Anárquico do Coronel Hansen",
  iconName: "Dog",
  gradient: "linear-gradient(to right, #5CBA57, #000000)",
  titleColorClass: "text-primary",
  borderColor: "#5CBA57",
  paragraphs: [
    "Dogtown é mais do que um subdistrito de Night City; é um estado dentro de um estado, uma anomalia anárquica e fortificada encravada no que um dia foi a promessa de Pacifica. Nenhuma outra área de Night City ilustra tão bem a falência do governo e o poder dos militares e dos senhores da guerra. Dogtown é um lembrete brutal de que, em um mundo sem lei, a força bruta é a moeda mais valiosa.",
    "Assim como o restante de Pacifica, Dogtown era parte do ambicioso plano de transformar a região em um paraíso turístico de luxo. A área que hoje compõe Dogtown incluía o gigantesco EBM Petrochem Stadium (conhecido como Stadium), que seria um centro de entretenimento de ponta. No entanto, o colapso econômico e o abandono corporativo de Pacifica nos anos 2060 deixaram essas construções inacabadas e a infraestrutura pela metade. A área se tornou um vasto canteiro de obras fantasma, repleto de prédios vazios e ruas desertas, um prato cheio para o surgimento da criminalidade.",
    "A virada definitiva para Dogtown aconteceu durante e após o Golpe Militar de 2069. O Coronel Kurt Hansen, um ex-militar das NUSA (Novos Estados Unidos da América) e líder de um grupo paramilitar chamado Barghest, viu uma oportunidade perfeita no caos de Night City. Ele e suas forças, compostas por mercenários, desertores e criminais de guerra, tomaram o controle de Dogtown.",
    "Hansen declarou a área uma Zona de Segurança Militar (ZSM) independente, cortando-a completamente do restante de Night City. Muros de concreto, checkpoints militares e uma vigilância implacável foram erguidos, transformando Dogtown em um feudo particular onde as leis de Night City não têm valor. A NCPD e o governo de Night City não têm jurisdição aqui; qualquer tentativa de interferência é recebida com força letal pelos Barghest. Essa independência, no entanto, veio à custa da liberdade e da segurança de seus habitantes.",
    "O Barghest é a única força de \"ordem\" em Dogtown, e sua palavra é a lei. Liderados por Hansen, eles controlam tudo: o acesso ao distrito, o comércio, a segurança e todas as atividades ilícitas. A economia de Dogtown é movida a contrabando, mercado negro de tecnologia, armas, drogas e informações. O Stadium, outrora um estádio esportivo, se tornou o centro nevrálgico dessa economia: um enorme mercado negro que funciona 24 horas por dia, onde se pode encontrar de tudo, desde chrome exótico até armas de combate de alto poder.",
    "As pessoas que vivem em Dogtown são uma mistura de refugiados de outras partes de Night City que buscam escapar da opressão corporativa, criminosos em fuga, mercenários desiludidos e aqueles que simplesmente não têm outro lugar para ir. A vida é brutal e a cada dia é uma luta pela sobrevivência, mas a ausência de regras corporativas e da NCPD atrai aqueles que anseiam por uma liberdade (ainda que perigosa) e oportunidades no submundo.",
    "Em Dogtown, a única \"figura política\" de fato é o Coronel Kurt Hansen. Ele age como um ditador militar, com poder absoluto sobre o distrito. As corporações não têm presença oficial ou legal em Dogtown, mas isso não significa que não haja influência. Muitas megacorporações, incluindo a Militech e a Arasaka, fazem negócios clandestinos com Hansen e os Barghest, comprando informações, recrutando mercenários ou usando Dogtown como um ponto de passagem para contrabando. A NetWatch, a agência global de segurança da internet, também monitora os Voodoo Boys e outras atividades de netrunning que podem ter ramificações em Dogtown.",
    "Apesar do controle férreo de Hansen, Dogtown é um lugar de constantes conflitos. Há disputas internas de poder entre as facções dos Barghest, rivalidades com gangues menores que tentam operar no distrito (como os Scavengers, que se aproveitam do caos para seus crimes de coleta de órgãos) e confrontos com grupos que tentam invadir a ZSM ou fugir de lá. Hansen é implacável com traidores e opositores, e a violência é usada como ferramenta de controle.",
    "A localização de Dogtown, adjacente a Pacifica, também gera tensões com os Voodoo Boys, que são netrunners extremamente perigosos e que veem a presença de Hansen como uma ameaça à sua própria autonomia e ao seu controle sobre o ciberespaço na região.",
    "Locais Conhecidos: Stadium (EBM Petrochem Stadium): Como mencionado, é o centro de operações dos Barghest e o maior mercado negro de Night City. Um lugar caótico, vibrante e cheio de oportunidades para quem não tem escrúpulos. Black Sapphire: Um cassino e resort de luxo que estava em construção e foi tomado por Hansen. Agora serve como sua fortaleza pessoal e centro de comando dos Barghest. Longshore Stacks: Uma área de depósitos e armazéns, ideal para esconderijo de contrabandistas e operações ilícitas.",
    "Em 2077, Dogtown é um testamento da capacidade humana de sobreviver e se adaptar, mesmo nos ambientes mais brutais. É uma zona de guerra constante, onde a liberdade é sinônimo de anarquia e a lei é ditada pelo cano da arma. É o sonho de Richard Night, pervertido e distorcido, um microcosmo da selvageria que permeia Night City."
  ],
  dominantGangs: ["Barghest (Kurt Hansen)"],
  majorCorporations: ["Militech (clandestine)", "Arasaka (clandestine)"]
};
