
import type { District } from './types';

export const heywood: District = {
  name: "Heywood: A Alma Multifacetada de Night City",
  iconName: "Home",
  gradient: "linear-gradient(to right, #FF6A00, #000000)",
  titleColorClass: "text-primary",
  borderColor: "#FF6A00",
  paragraphs: [
    "Heywood é o distrito mais populoso de Night City, um verdadeiro mosaico social e cultural que espelha as vastas desigualdades da metrópole. Não é tão opulento quanto Westbrook nem tão industrial quanto Santo Domingo, mas sua essência reside na sua capacidade de abrigar desde os luxuosos condomínios corporativos até as favelas mais humildes, tudo lado a lado. Heywood é onde a maioria dos cidadãos comuns de Night City vive e luta por sua sobrevivência diária.",
    "Heywood se desenvolveu como uma área residencial e comercial de grande porte, destinada a abrigar a crescente população de Night City. Sua localização estratégica, adjacente ao City Center, mas com custos de vida mais acessíveis, atraiu uma vasta gama de classes sociais. Com o tempo, a parte mais próxima do City Center e de Westbrook se tornou mais abastada, enquanto as áreas mais distantes e ao sul, como Wellsprings e Vista del Rey, se tornaram mais densamente povoadas e economicamente desfavorecidas.",
    "A evolução de Heywood foi marcada por um crescimento orgânico e menos planejado do que em outros distritos, resultando em uma arquitetura diversa que varia de prédios de escritórios modernos a edifícios de apartamentos em estilo \"slab\" (grandes blocos de concreto) e moradias improvisadas.",
    "Heywood é predominantemente o território dos Valentinos, uma das maiores e mais influentes gangues de Night City. Com suas raízes na cultura latina e um forte senso de família, honra e religiosidade (com uma interpretação bem peculiar), os Valentinos dominam as ruas de Wellsprings e grande parte de Vista del Rey. Eles controlam o tráfico de drogas, armas, implantes cibernéticos de baixo custo e uma vasta rede de pequenas empresas e negócios locais que pagam pela \"proteção\" da gangue. Sua presença é sentida em grafites, altares de rua e na música que ecoa pelas ruas.",
    "Embora os Valentinos sejam a força dominante, há pequenas células de outras gangues, como os 6th Street (que vêm de Santo Domingo e têm algumas operações nas áreas industriais de Heywood, especialmente nas fronteiras), e até mesmo grupos de Scavengers que espreitam nas sombras, buscando vítimas para seus comércios ilegais de órgãos e cibernéticos. Essas disputas menores levam a conflitos localizados, tiroteios e emboscadas que são comuns no dia a dia do distrito.",
    "As grandes megacorporações têm uma presença menos ostensiva em Heywood do que no City Center ou Westbrook, mas sua influência é inegável. Elas possuem propriedades, investem em negócios locais (muitas vezes como fachadas para operações mais obscuras) e controlam os empregos em algumas das poucas fábricas e centros logísticos do distrito. Empresas de segurança privada, muitas vezes subcontratadas por corporações, mantêm a ordem em áreas residenciais mais ricas e em edifícios de escritórios, mas raramente se aventuram nas favelas dominadas por gangues.",
    "A Biocorp, por exemplo, pode ter clínicas de baixo custo ou hospitais que atendem à população mais pobre, mas o acesso aos melhores tratamentos e tecnologias é reservado para quem pode pagar, gerando um contraste brutal na saúde pública do distrito.",
    "As figuras políticas em Heywood, como vereadores e representantes distritais, geralmente emergem da própria comunidade, mas sua autoridade é frágil e muitas vezes comprometida. A corrupção é endêmica, com políticos sendo influenciados (ou comprados) por gangues ou corporações para garantir seus interesses. Os orçamentos destinados a Heywood são frequentemente desviados, deixando as áreas mais carentes em condições precárias. A NCPD tem uma presença irregular; em algumas áreas, há patrulhas constantes, enquanto em outras, a lei é feita pela gangue dominante.",
    "Subdistritos Detalhados em Heywood: Wellsprings: O coração de Heywood, densamente povoado e dominado pelos Valentinos. É um bairro de vida vibrante nas ruas, com mercados, bares e comunidades fortes, mas também de violência e pobreza. As moradias são majoritariamente de classe média baixa e baixa. The Glen: Uma área mais afluente de Heywood, que faz fronteira com o City Center. Possui edifícios corporativos e condomínios de alto padrão, além de lojas e restaurantes mais sofisticados. É onde a classe média e alguns executivos menores escolhem viver, buscando um equilíbrio entre o acesso ao centro e a vida mais \"comunitária\". Vista del Rey: A parte mais pobre e industrial de Heywood, muitas vezes confundida com os arredores de Santo Domingo. É cheia de fábricas abandonadas, galpões e moradias precárias. É uma zona de alta criminalidade, onde os Valentinos enfrentam disputas por território e o ambiente é mais sombrio e desolado.",
    "Heywood é um palco constante de pequenos conflitos: disputas territoriais entre facções dos Valentinos, brigas com outras gangues que tentam invadir seu território, e confrontos com a NCPD ou segurança privada quando seus negócios são ameaçados. A vida aqui é uma luta diária contra a pobreza, a violência e a falta de oportunidades.",
    "Em 2077, Heywood é o microcosmo de Night City: uma cidade de riqueza e pobreza extremas, onde a fé e a família se misturam com a brutalidade das ruas. É um lugar onde a comunidade é forte, mas a opressão é constante, e a vida é barata, mas a vontade de sobreviver é inabalável."
  ],
  dominantGangs: ["Valentinos", "6th Street (borders)", "Scavengers"],
  majorCorporations: ["Biotechnica (clinics)", "Variadas (fachadas)"]
};
