
import type { District } from './types';

export const pacifica: District = {
  name: "Pacifica: O Paraíso Esquecido, Vazio e Perigoso",
  iconName: "BarChartBig",
  gradient: "linear-gradient(to right, #6992CF, #000000)",
  titleColorClass: "text-primary",
  borderColor: "#6992CF",
  paragraphs: [
    "Pacifica é a personificação do fracasso dos sonhos e das promessas quebradas em Night City. Originalmente concebido como um mega-resort de luxo e um paraíso turístico, o distrito se transformou em uma vasta e perigosa favela, dominada pela criminalidade e pela mais absoluta ausência de lei. Pacifica é um lembrete sombrio do que acontece quando as megacorporações perdem o interesse e abandonam um projeto, deixando seus habitantes à própria sorte.",
    "Nos anos 2060, Pacifica começou a ser desenvolvida com um ambicioso projeto de transformação em um destino turístico de ponta. Grandes corporações hoteleiras e de entretenimento investiram em construções luxuosas, como hotéis arranha-céus, resorts à beira-mar e shopping centers gigantescos. A promessa era de uma nova Costa de Ouro em Night City, atraindo turistas de alto poder aquisitivo de todo o mundo.",
    "No entanto, a crise econômica global e as Guerras Corporativas, que se intensificaram e se tornaram mais custosas, fizeram com que as corporações retirassem seus investimentos abruptamente. O projeto foi abandonado, deixando para trás construções inacabadas, esqueletos de prédios e uma infraestrutura parcialmente concluída. Muitos dos trabalhadores e migrantes que vieram para Pacifica em busca de oportunidades foram simplesmente deixados para trás, sem empregos e sem perspectivas.",
    "Com o abandono corporativo, Pacifica rapidamente se tornou um refúgio para os desamparados, os marginalizados e as comunidades que buscavam escapar do controle implacável das megacorporações e da NCPD. A área atraiu uma grande população de imigrantes, especialmente haitianos e caribenhos, que trouxeram sua cultura, seus dialetos e, o mais importante, sua expertise em netrunning e no submundo da internet.",
    "Foi nesse cenário que os Voodoo Boys ascenderam como a força dominante de Pacifica. Mais do que uma simples gangue, os Voodoo Boys são uma comunidade de netrunners e hackers extremamente perigosos, que combinam habilidades cibernéticas de ponta com práticas de vodu e uma profunda desconfiança em relação à tecnologia corporativa. Eles buscam a sabedoria do Old Net (a antiga internet) e operam com uma agenda própria, muitas vezes manipulando braindances e redes para alcançar seus objetivos, que incluem a proteção de sua comunidade e a busca por conhecimento.",
    "A gangue não se preocupa tanto com o controle de territórios físicos quanto com o controle do ciberespaço e a proteção de seus segredos. No entanto, eles mantêm uma presença forte e violenta em Pacifica para garantir que a área permaneça uma zona livre da influência corporativa e da NCPD.",
    "Em Pacifica, a NCPD não tem jurisdição, ou pelo menos, não tem vontade de exercê-la. O distrito é amplamente ignorado pelas autoridades de Night City, que o consideram um território perdido. Isso significa que a lei é feita pelas gangues, principalmente pelos Voodoo Boys, que impõem sua própria forma de justiça.",
    "Apesar do domínio dos Voodoo Boys, Pacifica é um lugar de constantes conflitos. Outras gangues menores tentam se estabelecer, e criminosos oportunistas exploram o vácuo de poder. Os Animals, por exemplo, ocasionalmente se aventuram em Pacifica em busca de brigas e para expandir suas operações de drogas. A violência é endêmica, com tiroteios e confrontos sendo uma rotina.",
    "Em Pacifica, não há figuras políticas reconhecidas pelo governo de Night City. A liderança é exercida pelos próprios líderes dos Voodoo Boys, que agem como protetores e líderes de sua comunidade, garantindo sua autonomia e resistindo a qualquer tentativa de controle externo. A economia é baseada no mercado negro, contrabando, tecnologia roubada e serviços de netrunning ilícitos.",
    "Subdistritos e Locais Conhecidos em Pacifica: Coastview: A parte mais desenvolvida de Pacifica, com os esqueletos dos antigos resorts de luxo. É aqui que se encontra o Grand Imperial Mall, um shopping center gigante que nunca foi terminado e que se tornou uma espécie de \"cidade dentro da cidade\", com seus próprios mercados clandestinos, abrigos e comunidades vivendo em suas ruínas. Capitão Caliente: Uma área mais central de Pacifica, com moradias improvisadas e mercados de rua que servem a população local. West Wind Estate: Uma área residencial inacabada que se tornou um labirinto de prédios abandonados e favelas verticais.",
    "Pacifica é um distrito de uma beleza distópica: palmeiras retorcidas e uma praia poluída contrastam com os imponentes prédios abandonados. A paisagem é um lembrete constante das promessas não cumpridas e da negligência corporativa. No entanto, em meio a essa decadência, os habitantes de Pacifica, impulsionados pela necessidade e pela solidariedade, criaram uma cultura de resistência e autossuficiência.",
    "Em 2077, Pacifica é uma zona de perigo e liberdade, onde a tecnologia de ponta dos Voodoo Boys se choca com a pobreza e a falta de infraestrutura. É um lugar onde a vida é barata, a esperança é um luxo, mas a capacidade de sobreviver e se adaptar é inabalável."
  ],
  dominantGangs: ["Voodoo Boys", "Animals"],
  majorCorporations: []
};
