
import type { District } from './types';

export const santoDomingo: District = {
  name: "Santo Domingo: O Motor Industrial e o Caldeirão de Classes",
  iconName: "Factory",
  gradient: "linear-gradient(to right, #4599FF, #000000)",
  titleColorClass: "text-primary",
  borderColor: "#4599FF",
  paragraphs: [
    "Santo Domingo é o pulmão e o músculo de Night City, o distrito industrial e de moradias populares que mantém a cidade funcionando. É aqui que a maior parte da produção industrial e da infraestrutura pesada de Night City está localizada, um lugar onde o trabalho duro e a vida operária são a norma. Mas não se engane, Santo Domingo também é um caldeirão de conflitos, onde a poluição e a decadência se misturam com a resiliência de seus habitantes e a força das gangues que controlam suas ruas.",
    "Desde os primórdios de Night City, a área que se tornaria Santo Domingo foi designada para abrigar a indústria pesada. Sua proximidade com o porto e com as principais vias de transporte a tornou ideal para fábricas, refinarias de petroquímicos, usinas de energia e enormes complexos de armazenamento. O desenvolvimento foi impulsionado por megacorporações como a Petrochem (líder em energia e combustíveis) e outras empresas de manufatura que buscavam mão de obra barata e um ambiente com menos regulamentação governamental.",
    "A arquitetura de Santo Domingo é funcional e robusta, com enormes galpões industriais, tubulações expostas, chaminés e blocos de apartamentos de baixo custo que abrigam a vasta população de trabalhadores braçais. A poluição do ar é uma constante, e o ambiente é frequentemente cinzento e opressivo.",
    "Santo Domingo é um distrito disputado por várias gangues, mas com a forte presença e influência dos 6th Street. Originalmente formados por veteranos de guerra que se sentiam abandonados pela sociedade e pelas corporações, os 6th Street veem-se como os \"verdadeiros\" guardiões do povo de Night City, mas operam como uma gangue, impondo sua própria lei e protegendo (ou extorquindo) os trabalhadores do distrito. Eles controlam o tráfico de armas, a proteção de pequenos negócios e organizam eventos de combate e rachas ilegais. Sua ideologia de \"justiça\" e \"serviço\" atrai muitos que se sentem marginalizados.",
    "Além dos 6th Street, Santo Domingo também é um território frequentado pelos Maelstrom, especialmente nas zonas mais sombrias e abandonadas do distrito, como o Rancho Coronado. Os Maelstrom, com suas modificações cibernéticas extremas e seu comportamento psicótico, buscam confrontos e operam laboratórios de drogas e implantes ilegais nas ruínas industriais. A rivalidade entre os 6th Street e os Maelstrom é uma fonte constante de violência em Santo Domingo.",
    "Os Animals, outra gangue focada em aprimoramentos físicos e uso de drogas de combate, também têm uma presença em áreas específicas de Santo Domingo, especialmente em clubes de luta clandestinos ou academias de força.",
    "As megacorporações têm uma presença massiva em Santo Domingo, mas de uma forma mais extrativa do que em outros distritos. Empresas como a Petrochem dominam o cenário com suas gigantescas refinarias e instalações de processamento. A Militech também possui bases de treinamento e centros de logística na região, dada a natureza industrial do distrito.",
    "Essas corporações são as principais empregadoras em Santo Domingo, mas as condições de trabalho são frequentemente precárias, os salários são baixos e os direitos dos trabalhadores são quase inexistentes. A população local é explorada, e as corporações se beneficiam da mão de obra barata e das regulamentações ambientais frouxas.",
    "A influência política em Santo Domingo é complexa. O Conselho Municipal tem pouco controle real sobre o distrito, com a autoridade de fato sendo dividida entre as megacorporações e as gangues dominantes. Os vereadores locais têm dificuldade em fazer valer a lei e a ordem, e muitos são corruptos ou intimidados pelas gangues.",
    "A NCPD tem uma presença esporádica e reativa, geralmente intervindo apenas quando os interesses corporativos estão em risco ou quando a violência atinge níveis insustentáveis. Para a maioria dos moradores de Santo Domingo, a \"lei\" é ditada pelas gangues que controlam seu quarteirão.",
    "Subdistritos Detalhados: Rancho Coronado: Uma vasta área industrial e de moradias populares. É o lar da maior parte da população de Santo Domingo e um reduto dos 6th Street. Possui grandes fábricas, complexos de apartamentos e é um local de muitos conflitos. A poluição é severa, e a vida é dura. Arroyo: Outra área industrial e residencial, com muitas construções antigas e um ambiente ainda mais desolado que Rancho Coronado. É um local de intensa atividade de gangues e onde a pobreza é ainda mais evidente. Fábricas abandonadas e armazéns vazios são esconderijos comuns para atividades criminosas. The Glen (parte de Santo Domingo): Embora a maior parte de The Glen esteja em Heywood, uma porção se estende até Santo Domingo, marcando a transição entre o distrito mais populoso e a zona industrial.",
    "Santo Domingo é um palco constante de brigas e disputas. Os 6th Street frequentemente se envolvem em tiroteios com os Maelstrom e outras gangues que tentam se infiltrar em seu território. Conflitos por controle de rotas de contrabando, por fábricas abandonadas e por influência sobre a população são a norma. A vida diária é uma luta para sobreviver em um ambiente hostil, onde os recursos são escassos e a esperança é uma commodity rara.",
    "Em 2077, Santo Domingo é o retrato da resiliência e da exploração em Night City. É o distrito que mantém as engrenagens da metrópole girando, mas à custa da saúde e da segurança de seus próprios habitantes. É um lugar onde a comunidade é forte, mas a batalha contra as corporações e a violência é uma realidade diária e implacável."
  ],
  dominantGangs: ["6th Street", "Maelstrom", "Animals"],
  majorCorporations: ["Petrochem", "Militech"]
};
