
import type { District } from './types';

export const watson: District = {
  name: "Watson: O Berço e o Abandono",
  gradient: "linear-gradient(to right, #DB0000, #000000)",
  titleColorClass: "text-primary",
  borderColor: "#DB0000",
  paragraphs: [
    "Watson é um dos distritos mais antigos de Night City, e sua história é um reflexo perfeito da evolução (ou involução) da cidade. Localizado ao norte do City Center, Watson era, em seus primeiros dias, o coração financeiro e comercial de Night City. Seus edifícios, muitos deles construídos no final do século XX e início do XXI, abrigavam bancos, escritórios corporativos e lojas de luxo. A vida aqui era vibrante, um verdadeiro símbolo do progresso e da riqueza da cidade.",
    "A glória de Watson, no entanto, começou a desmoronar com as Guerras Corporativas, especialmente a Quarta Guerra. Com os bombardeios e a instabilidade econômica, as megacorporações mais poderosas começaram a migrar para o City Center, buscando mais segurança e maior status. Watson foi progressivamente abandonado por seus antigos \"donos\" corporativos. A infraestrutura, antes impecável, começou a decair. Prédios foram desocupados, a manutenção parou, e a área se tornou um terreno fértil para a criminalidade.",
    "A explosão da bomba nuclear na Arasaka Tower em 2023, embora tenha afetado mais diretamente o City Center, também reverberou por Watson, causando mais destruição e acelerando seu declínio. Muitos negócios fecharam, e a população de menor poder aquisitivo começou a se concentrar ali, atraída pelos aluguéis mais baixos e pela menor presença da lei (e das corporações).",
    "Com o êxodo corporativo, Watson se tornou um refúgio para imigrantes e minorias, especialmente comunidades asiáticas, que trouxeram suas culturas e estabeleceram bairros vibrantes como Little China e Kabuki. Little China é um labirinto de ruas estreitas, mercados de rua e lojas de todos os tipos, pulsando com a vida de seus moradores. Kabuki, por sua vez, é conhecido por seus \"ripperdocs\" clandestinos, clínicas de modificação corporal e uma vida noturna agitada e perigosa.",
    "Essa descentralização do poder corporativo abriu espaço para o surgimento e o fortalecimento das gangues. Os Tyger Claws, uma gangue japonesa com forte influência e um estilo de vida que mescla tradições Yakuza com um fascínio por aprimoramentos cibernéticos e motocicletas de alta performance, se estabeleceram como a força dominante em Watson, especialmente em Kabuki e Little China. Eles controlam o tráfico de cibernéticos ilegais, drogas e a prostituição, operando seus negócios à vista de todos, mas com um código de honra distorcido.",
    "Outras gangues menores também disputam território em Watson, como alguns grupos de Maelstrom que se escondem nas áreas industriais abandonadas do Northside Industrial District (NID). O NID é uma paisagem de fábricas enferrujadas e armazéns vazios, um local perfeito para atividades criminosas e confrontos sangrentos. A NCPD (Night City Police Department) tem uma presença limitada em Watson, muitas vezes optando por patrulhar as áreas mais \"nobres\" e deixar as gangues se resolverem entre si nas zonas menos visíveis.",
    "Apesar de ser um distrito menos valorizado pelas grandes megacorporações, Watson ainda sente a influência delas, embora de forma mais indireta. Empresas de tecnologia menores e startups tentam se estabelecer na região, buscando inovar em um ambiente mais \"livre\". O governo de Night City, através de vereadores locais e figuras políticas menos expressivas, tenta manter uma fachada de controle, mas a realidade é que o poder de fato está nas mãos dos Tyger Claws e de quem mais tiver mais edinhos (dinheiro) para bancar a influência.",
    "Locais conhecidos em Watson, além de Little China e Kabuki, incluem o Arasaka Waterfront, que, apesar do nome, não é mais um ponto forte da Arasaka, mas um lembrete da antiga glória corporativa, e vários mercados de rua onde você pode encontrar de tudo, desde comida de rua deliciosa até tecnologia duvidosa e armas.",
    "Em 2077, Watson é um distrito de contrastes gritantes: a efervescência cultural de Little China e Kabuki convive com a decadência do NID e a constante ameaça da violência das gangues. É o lugar onde a maioria dos recém-chegados em Night City começa sua jornada, um campo de testes brutal para quem quer sobreviver na cidade dos sonhos e pesadelos."
  ]
};
