
import type { District } from './types';

export const westbrook: District = {
  name: "Westbrook: O Luxo Deteriorado e a Ordem dos Tyger Claws",
  gradient: "linear-gradient(to right, #3D009E, #000000)",
  titleColorClass: "text-primary",
  borderColor: "#3D009E",
  paragraphs: [
    "Westbrook é o distrito que mais se aproxima do ideal de Richard Night para uma utopia de luxo e entretenimento, mas com o tempero distópico e perigoso de Night City. É o playground dos ricos, das celebridades e dos executivos corporativos, mas também é um lugar onde a influência das megacorporações se mistura com o domínio implacável dos Tyger Claws. Sua história é a de uma área que ascendeu rapidamente ao topo, mas que por baixo da superfície polida, esconde uma rede complexa de controle, poder e decadência.",
    "Desde o planejamento original de Night City, Westbrook foi destinada a ser a área de alto padrão. Com investimentos massivos de corporações como a Arasaka e outras empresas de entretenimento e tecnologia, o distrito se desenvolveu rapidamente, com construções de luxo, condomínios exclusivos e centros de lazer de última geração. A ideia era criar um refúgio para a elite, longe do caos dos distritos mais pobres, onde o estilo de vida ostentoso fosse a regra.",
    "Westbrook é dividido em três subdistritos principais, cada um com sua própria nuance, mas todos refletindo a opulência geral do distrito: Japantown, North Oak, e Charter Hill.",
    "Japantown: O coração cultural e de entretenimento de Westbrook. É o epicentro da cultura japonesa em Night City, com arquitetura deslumbrante, clubes noturnos exclusivos (como o famoso Clouds, que oferece braindances personalizados), restaurantes de alta gastronomia e boutiques de luxo. É um lugar de excessos e ostentação, permanentemente iluminado por néons gigantes. Japantown é um símbolo da influência da Arasaka e das megacorporações japonesas na cidade, servindo como uma vitrine de sua riqueza e poder cultural.",
    "North Oak: A área mais exclusiva e isolada de Westbrook. Aqui estão as mansões gigantescas, os condomínios fechados e os bunkers de luxo das famílias mais ricas e poderosas de Night City. A segurança é privada e impenetrável, protegendo seus moradores de qualquer ameaça externa. É o verdadeiro lar dos CEOs e das celebridades, um oásis de tranquilidade (relativa) em meio ao caos da cidade.",
    "Charter Hill: Uma área que serve como ponte entre o glamour de Japantown e a exclusividade de North Oak. Possui muitos prédios corporativos de médio porte e apartamentos de alto padrão, além de centros comerciais e escritórios de empresas que atendem à elite de Westbrook. Embora mais acessível que North Oak, ainda mantém um alto padrão de vida e segurança.",
    "Apesar de ser um distrito de elite, Westbrook está sob o controle esmagador dos Tyger Claws. Diferente de outras gangues que operam nas sombras, os Tyger Claws em Westbrook (especialmente em Japantown) são uma força quase onipresente e abertamente dominante. Eles são uma gangue de origem japonesa, conhecida por seu código de honra distorcido (baseado nas tradições Yakuza), seu fascínio por aprimoramentos cibernéticos e suas motocicletas neon.",
    "Os Tyger Claws controlam grande parte do submundo do entretenimento de Westbrook: o tráfico de cibernéticos de luxo, a prostituição (incluindo o lucrativo mercado de braindances), extorsão de negócios locais e outros esquemas ilícitos. Sua presença é tão forte que a NCPD (Night City Police Department) muitas vezes faz vista grossa para suas operações, preferindo que a gangue mantenha uma certa \"ordem\" nas ruas, desde que isso não interfira nos interesses das megacorporações que têm presença no distrito. Essa \"paz podre\" é uma característica marcante de Westbrook.",
    "As figuras políticas de Westbrook são frequentemente ligadas às corporações ou são meros fantoches dos interesses corporativos. A influência da Arasaka é palpável, com muitos de seus executivos residindo em North Oak e mantendo conexões profundas com os negócios em Japantown.",
    "Os conflitos em Westbrook são menos sobre guerra de gangues territorial em grande escala e mais sobre disputas de poder e controle sobre mercados lucrativos. Facções menores tentam roubar clientes dos Tyger Claws ou sabotar seus negócios, resultando em assassinatos discretos e confrontos localizados.",
    "Apesar do glamour e da riqueza, Westbrook, assim como outras partes de Night City, não é imune à decadência. Há bolsões de pobreza e áreas menos cuidadas. A dependência de tecnologia e a busca incessante por aprimoramentos cibernéticos levam muitos a vícios e problemas de saúde mental, mesmo entre os mais ricos.",
    "Em 2077, Westbrook é um contraste chocante: o auge do luxo e da tecnologia convivendo com uma violência organizada e uma vigilância constante. É um lugar onde a superficialidade e a ostentação escondem a brutalidade de uma cidade onde o poder e o dinheiro ditam todas as regras."
  ],
  dominantGangs: ["Tyger Claws"],
  majorCorporations: ["Arasaka", "Diversas de entretenimento e luxo"]
};
